### ISSUE TITLE
Problem with ftp upload from azure devops

### ISSUE THREAD

**Issue by Alword** [inwords/InWords#63]
I believe my pipeline is setup ok but FTP seems to not upload any files. I have listed the FTP log and also my YAML.

It appears my build.artifactstagingdirectory is empty.

FTP Message:
```
[section]Starting: FTP Upload: $(build.artifactstagingdirectory)

Task         : FTP Upload
Description  : FTP Upload
Version      : 1.142.2
Author       : Microsoft Corporation
Help         : Upload files to a remote machine using the File Transfer Protocol (FTP), or securely with FTPS.  [More Information](http://go.microsoft.com/fwlink/?LinkId=809084).

connecting to: api.xxx.com:21
connected: Microsoft FTP Service
uploading files to remote directory: /
files uploaded: 0, files skipped: 0, directories processed: 1, total: 1, remaining: 2, remote directory successfully created/verified: /
files uploaded: 0, files skipped: 0, directories processed: 2, total: 2, remaining: 1, remote directory successfully created/verified: /
files uploaded: 1, files skipped: 0, directories processed: 2, total: 3, remaining: 0, successfully uploaded: D:\a\1\a\xxx.API.zip to: /xxx.API.zip
FTP upload successful 
host: api.xxx.com
path: /
files uploaded: 1
files skipped: 0
directories processed: 2
disconnecting from: api.xxx.com
disconnected
##[section]Finishing: FTP Upload: $(build.artifactstagingdirectory)
```
But I am building to this directory.

My YAML is below:

```
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: $(build.artifactstagingdirectory)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: FtpUpload@1
  displayName: 'FTP Upload: $(build.artifactstagingdirectory)'
  inputs:
    credentialsOption: inputs
    serverUrl: 'ftp://api.xxx.com'
    username: xxx
    password: ‘xxx’
    rootDirectory: '$(build.artifactstagingdirectory)'
    remoteDirectory: /
    preservePaths: true
    trustSSL: true
```
I would appreciate any assistance. Thanks
